cfbets/bets/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from bets import views
from bets.views import AllBetsJson, MyCompletedBetsJson, AdminBetsJson

app_name = 'bets'
urlpatterns = [
    url(r'^$', views.bets),
    url(r'^my_bets/', views.my_bets),
    url(r'^open_bets/', views.open_bets),
    url(r'^all_bets/', views.all_bets),
    url(r'^all_bets_json/', AllBetsJson.as_view(), name='all_bets_json'),
    url(r'^my_completed_bets_json/', MyCompletedBetsJson.as_view(), name='my_completed_bets_json'),
    url(r'^admin_bets_json/', AdminBetsJson.as_view(), name='admin_bets_json'),
    url(r'^your_stats/', views.your_stats),
    url(r'^global_stats/', views.global_stats),
    url(r'^process_place_bets/(?P<next_url>.*$)', views.place_bets_form_process, name='place_bets_form_process'),
    url(r'^check_duplicate_bet/', views.check_duplicate_bet),
    url(r'^remove_prop_bet/', views.remove_prop_bet),
    url(r'^accept_prop_bet/', views.accept_prop_bet),
    url(r'^set_prop_bet/', views.set_prop_bet),
    url(r'^undo_prop_bet/', views.undo_prop_bet),
    url(r'^admin_bets/', views.admin_bets),
]

cfbets/cfbets/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.views.generic.base import TemplateView
from cfbets.views import welcome, sign_up, profile

urlpatterns = [
    url(r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('assets/icons/favicon.ico'),
            permanent=False),
        name="favicon"),
    url(r'^bets/', include('bets.urls', namespace='bets', app_name='bets')),
    url(r'^$', welcome),
    url(r'^login/$', auth_views.login, {'template_name': 'base_login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^sign_up/$', sign_up),
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registration/password_reset_form.html'}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'registration/password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^profile/', profile),
    url(r'^admin/', admin.site.urls),
]

cfbets/bets/forms.py
from django import forms
from django.utils import timezone
import datetime as dt


class PlaceBetsForm(forms.Form):
    bet = forms.CharField(label='Bet', max_length=500, widget=forms.TextInput(
        attrs={'placeholder': 'E.g. Clemson -48.5 over USCjr', 'autocomplete': 'off'}))

    bet_amount = forms.IntegerField(
        label='Bet Amount (USD)',
        initial=5,
        min_value=1,
        max_value=20,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    qty_allowed = forms.IntegerField(
        label='Qty Allowed',
        initial=2,
        min_value=1,
        max_value=10,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    bet_expiration_date = forms.DateTimeField(
        label='Expiration (mm/dd/yyyy 24hr eastern time)',
        help_text='Default is one week from today. Bet will no longer be available for others to accept after this datetime.',
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    def clean_bet_expiration_date(self):
        bet_expiration_date = self.cleaned_data['bet_expiration_date']

        if bet_expiration_date < timezone.now():
            raise forms.ValidationError("Datetime can't be in the past.")

        return bet_expiration_date

cfbets/bets/views.py
import json
import requests
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django_datatables_view.base_datatable_view import BaseDatatableView
from common.stats import *
from django.conf import settings
from bets.forms import PlaceBetsForm
from bets.models import ProposedBet, AcceptedBet, UserProfile, UserProfileAudit, User
from django.db.models import Sum

# Create your views here.

def bets(request):
    return HttpResponseRedirect('/bets/my_bets')

@login_required(login_url='/login/')
def your_stats(request):

    # get the current user
    current_user = request.user

    # get win, loss, tie stats
    total_wins = get_total_wins(current_user)
    total_losses = get_total_losses(current_user)
    total_ties = get_total_ties(current_user)
    win_percentage = get_win_percentage(current_user)

    # throw it in a dictionary
    win_loss_tie = {
        'wins': total_wins,
        'losses': total_losses,
        'ties': total_ties,
        'win_percentage': win_percentage}

    # get total proposed and total proposed won bets
    total_proposed = get_total_proposed(current_user)

    # get total bets you accepted and total bets won you accepted
    total_accepted = get_total_accepted(current_user)

    # get bet against report
    bet_against_report = get_bet_against_report(current_user)

    # get total bets by week list (both proposed and accepted)
    total_bets_by_week = get_total_bets_by_week(current_user)

    # get total money by week list
    total_money_by_week = get_total_money_by_week(current_user)

    # get week start info
    week_start = get_week_start()

    return render(request,
                  'bets/base_your_stats.html',
                  {'nbar': 'stats',
                   'win_loss_tie': win_loss_tie,
                   'total_proposed': total_proposed,
                   'total_accepted': total_accepted,
                   'bet_against_report': bet_against_report,
                   'week_start': week_start,
                   'total_bets_by_week': total_bets_by_week,
                   'total_money_by_week': total_money_by_week})

@login_required(login_url='/login/')
def global_stats(request):

    # get the current user
    current_user = request.user

    global_stats = get_global_stats
    global_betting_report = get_global_betting_report
    global_bettingest_couples = get_bettingest_couples
    global_total_bets_by_week = get_global_total_bets_by_week

    # get week start info
    week_start = get_week_start()

    return render(request,
                  'bets/base_global_stats.html',
                  {'nbar': 'stats',
                   'global_stats': global_stats,
                   'global_total_bets_by_week': global_total_bets_by_week,
                   'week_start': week_start,
                   'global_betting_report': global_betting_report,
                   'global_bettingest_couples': global_bettingest_couples})

@login_required(login_url='/login/')
def my_bets(request):

    # get the current user
    current_user = request.user

    # get all their proposed bets that have remaining bets and have end dates
    # past now
    your_open_bets = ProposedBet.objects.filter(
        user=current_user,
        remaining_wagers__gt=0,
        end_date__gt=timezone.now(),
        won_bet__isnull=True)

    # your active bets, i.e. those bets you have accepted and your bets that
    # other users have accepted
    your_accepted_bets = AcceptedBet.objects.filter(
        accepted_user=current_user, accepted_prop__won_bet__isnull=True)

    your_bets_accepted_by_others = AcceptedBet.objects.filter(
        accepted_prop__user=current_user, accepted_prop__won_bet__isnull=True)

    your_active_bets = your_accepted_bets | your_bets_accepted_by_others

    your_active_bets_count = your_active_bets.count()

    # your active bets, total money bet
    your_active_bets_total_amount = your_active_bets.aggregate(
        Sum('accepted_prop__prop_wager'))

    your_active_bets_total_amount = your_active_bets_total_amount.values()[0]

    return render(request,
                  'bets/base_my_bets.html',
                  {'nbar': 'my_bets',
                   'your_open_bets': your_open_bets,
                   'your_active_bets': your_active_bets,
                   'your_active_bets_count': your_active_bets_count,
                   'your_active_bets_total_amount': your_active_bets_total_amount})

@login_required(login_url='/login/')
def open_bets(request):

    # used for expiring soon and new bet tags
    tomorrow = timezone.now() + timezone.timedelta(days=1)
    yesterday = timezone.now() + timezone.timedelta(days=-1)

    # get the current user
    current_user = request.user

    # get all open prop bets from other users
    open_bets = ProposedBet.objects.filter(
        remaining_wagers__gt=0,
        end_date__gt=timezone.now(),
        won_bet__isnull=True).exclude(
        user=current_user)

    # get all bets created in past 24 hours
    new_bets = ProposedBet.objects.filter(
        remaining_wagers__gt=0,
        end_date__gt=timezone.now(),
        created_on__gt=yesterday,
        won_bet__isnull=True).exclude(
        user=current_user)

    # get all bets expiring in next 24 hours
    closing_soon_bets = ProposedBet.objects.filter(
        remaining_wagers__gt=0,
        end_date__gt=timezone.now(),
        end_date__lt=tomorrow,
        won_bet__isnull=True).exclude(
        user=current_user)

    return render(request,
                  'bets/base_open_bets.html',
                  {'nbar': 'open_bets',
                   'open_bets': open_bets,
                   'new_bets': new_bets,
                   'closing_soon_bets': closing_soon_bets})

@login_required(login_url='/login/')
def all_bets(request):

    # get all active accepted bets
    all_active_bets = AcceptedBet.objects.filter(
        accepted_prop__won_bet__isnull=True)

    return render(request, 'bets/base_all_bets.html',
                  {'nbar': 'all_bets', 'all_active_bets': all_active_bets})

class MyCompletedBetsJson(BaseDatatableView):
    order_columns = ['accepted_prop__prop_text',
                     'accepted_prop__prop_wager', '', '']

    def get_initial_queryset(self):
        current_user = self.request.user
        your_accepted_bets = AcceptedBet.objects.filter(
            accepted_user=current_user, accepted_prop__won_bet__isnull=False)

        your_bets_accepted_by_others = AcceptedBet.objects.filter(
            accepted_prop__user=current_user, accepted_prop__won_bet__isnull=False)

        your_closed_bets = your_accepted_bets | your_bets_accepted_by_others
        return your_closed_bets.order_by('-accepted_prop__modified_on')

    def filter_queryset(self, qs):
        sSearch = self.request.GET.get(u'search[value]', None)

        if sSearch:
            qs = qs.filter(
                accepted_prop__prop_text__istartswith=sSearch) | qs.filter(
                accepted_user__first_name__istartswith=sSearch) | qs.filter(
                accepted_user__last_name__istartswith=sSearch) | qs.filter(
                accepted_prop__user__first_name__istartswith=sSearch) | qs.filter(
                    accepted_prop__user__last_name__istartswith=sSearch)

        return qs

    def prepare_results(self, qs):
        json_data = []
        current_user = self.request.user

        for item in qs:

            # figure out who the bet was against
            bet_against_user = ''
            if item.accepted_prop.user == current_user:
                bet_against_user = item.accepted_user.get_full_name()
            else:
                bet_against_user = item.accepted_prop.user.get_full_name()

            who_won = ''
            if item.accepted_prop.get_won_bet_display() == "Win":
                who_won = item.accepted_prop.user.get_full_name()
            elif item.accepted_prop.get_won_bet_display() == "Loss":
                who_won = item.accepted_user.get_full_name()
            else:
                who_won = 'push'

            json_data.append([
                item.accepted_prop.prop_text,
                '$' + str(item.accepted_prop.prop_wager),
                bet_against_user,
                who_won
            ])

        return json_data

class AllBetsJson(BaseDatatableView):
    order_columns = [
        'accepted_prop__user',
        'accepted_user',
        'accepted_prop__prop_text',
        'accepted_prop__prop_wager',
        '']

    def get_initial_queryset(self):
        return AcceptedBet.objects.filter(
            accepted_prop__won_bet__isnull=False).order_by('-accepted_prop__modified_on')

    def filter_queryset(self, qs):
        sSearch = self.request.GET.get(u'search[value]', None)

        if sSearch:
            qs = qs.filter(
                accepted_prop__prop_text__istartswith=sSearch) | qs.filter(
                accepted_user__first_name__istartswith=sSearch) | qs.filter(
                accepted_user__last_name__istartswith=sSearch) | qs.filter(
                accepted_prop__user__first_name__istartswith=sSearch) | qs.filter(
                    accepted_prop__user__last_name__istartswith=sSearch)

        return qs

    def prepare_results(self, qs):
        json_data = []
        for item in qs:

            who_won = ''
            if item.accepted_prop.get_won_bet_display() == "Win":
                who_won = item.accepted_prop.user.get_full_name()
            elif item.accepted_prop.get_won_bet_display() == "Loss":
                who_won = item.accepted_user.get_full_name()
            else:

cfbets/bets/templates/bets/base_admin_bets.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_head %}
<script type="text/javascript">
    var ADMIN_BETS_JSON_URL = '{% url "bets:admin_bets_json" %}';

    // translations for datatables
    var dt_language = {
        "emptyTable":     "{% trans "No data available in table" %}",
        "info":           "{% trans "Showing _START_ to _END_ of _TOTAL_ entries" %}",
        "infoEmpty":      "{% trans "Showing 0 to 0 of 0 entries" %}",
        "infoFiltered":   "{% trans "(filtered from _MAX_ total entries)" %}",
        "infoPostFix":    "",
        "thousands":      ",",
        "lengthMenu":     "{% trans "Show _MENU_ entries" %}",
        "loadingRecords": "{% trans "Loading..." %}",
        "processing":     "{% trans "Processing..." %}",
        "search":         "{% trans "Search:" %}",
        "zeroRecords":    "{% trans "No matching records found" %}",
        "paginate": {
            "first":      "{% trans "First" %}",
            "last":       "{% trans "Last" %}",
            "next":       "{% trans "Next" %}",
            "previous":   "{% trans "Previous" %}"
        },
        "aria": {
            "sortAscending":  "{% trans ": activate to sort column ascending" %}",
            "sortDescending": "{% trans ": activate to sort column descending" %}"
        }
    }
</script>
{% endblock %}

{% block base_content %}
<div class="container">
<h1>Admin Bets</h1>

    <div class="container">
        <h3>Expired Prop Bets Without Winner</h3>
        <p>These prop bets have at least one accepted bet and are expired.</p>
        {% if expired_prop_bets %}
            <table class="table table-striped table-bordered table-condensed" id="propExpired">
                <thead>
                    <tr>
                        <th>Proposer</th>
                        <th>Prop Bet</th>
                        <th>End Date</th>
                        <th>Win / Loss</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bet in expired_prop_bets %}
                    <tr>
                        <td>{{ bet.user.get_full_name }}</td>
                        <td>{{ bet.prop_text }}</td>
                        <td>{{ bet.end_date|date:"M d Y H:i" }}</td>
                        <td style="text-align: center; vertical-align: middle">
                            <a href="/bets/set_prop_bet?id={{ bet.id }}&status=Win" class="btn btn-primary btn-xs grid-button open-SetPropBet">Win</a>
                            <a href="/bets/set_prop_bet?id={{ bet.id }}&status=Loss" class="btn btn-danger btn-xs grid-button open-SetPropBet">Loss</a>
                            <a href="/bets/set_prop_bet?id={{ bet.id }}&status=Tie" class="btn btn-default btn-xs grid-button open-SetPropBet">Push</a>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No bets to mark.</p>
        {% endif %}
    </div>

    <div class="container">
        <h3>Open Prop Bets Without Winner</h3>
        <p>These prop bets have at least one accepted bet but enddate has not passed.</p>
        {% if open_prop_bets %}
        <table class="table table-striped table-bordered table-condensed" id="propNotExpired">
            <thead>
                <tr>
                    <th>Proposer</th>
                    <th>Prop Bet</th>
                    <th>End Date</th>
                    <th>Win / Loss</th>
                </tr>
            </thead>
            <tbody>
                {% for bet in open_prop_bets %}
                <tr>
                    <td>{{ bet.user.get_full_name }}</td>
                    <td>{{ bet.prop_text }}</td>
                    <td>{{ bet.end_date|date:"M d Y H:i" }}</td>
                    <td style="text-align: center; vertical-align: middle">
                        <a id="win-prop-btn" href="/bets/set_prop_bet?id={{ bet.id }}&status=Win" class="btn btn-primary btn-xs grid-button open-SetPropBet">Win</a>
                        <a id="loss-prop-btn" href="/bets/set_prop_bet?id={{ bet.id }}&status=Loss" class="btn btn-danger btn-xs grid-button open-SetPropBet">Loss</a>
                        <a id="tie-prop-btn" href="/bets/set_prop_bet?id={{ bet.id }}&status=Tie" class="btn btn-default btn-xs grid-button open-SetPropBet">Push</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No bets to mark.</p>
        {% endif %}
    </div>

    <div class="container">
        <h3>All Closed Prop bets</h3>
        <p>These prop bets have a marked winner (and have at least one accepted bet).</p>
        <table class="table table-striped table-bordered table-condensed" id="propCompleted">
            <thead>
                <tr>
                    <th>{% trans "Proposer" %}</th>
                    <th>{% trans "Prop Bet" %}</th>
                    <th>{% trans "Win / Loss" %}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

</div>

<!-- Undo Prop Bet modal -->
<div class="modal fade" id="undoPropBet" tabindex="-1" role="dialog" aria-labelledby="UndoPropBet">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="UndoPropBet">Undo Prop Bet?</h4>
            </div>
            <div class="modal-body">
                <p>Undo <i>(aka remove win/loss status)</i> from  the following bet:</p>
                <p><strong><span id="betUser"></span> proposed "<span id="betId"></span>"</strong></p>
                <p><small>Note: This will also update winnings amounts for users with any accepted bets on this prop.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <a id="undo-bet-btn" class="btn btn-warning">Undo</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block morejs %}
var dt_table = $('#propCompleted').dataTable({
    language: dt_language,  // global variable defined in html
    order: [],
    lengthMenu: [10, 25, 50, 100],
    columnDefs: [
        {orderable: true,
        searchable: true,
        className: "center",
        targets: [0, 1]
        },
        {orderable: false,
        targets: [-1, -2]
        },
        {targets: -1,
        createdCell: function (td, cellData, rowData, row, col) {
        $(td).html('<a href="#" data-href="/bets/undo_prop_bet?id=' + cellData[2] +
            '" data-target="#undoPropBet" data-toggle="modal" data-id1="' + cellData[1] +
            '" data-id2="' + cellData[0] + '" title="Undo prop bet" class="btn btn-warning btn-xs open-UndoPropBet">undo</a></td>')
        }
        }
    ],
    searching: true,
    processing: true,
    serverSide: true,
    stateSave: false,
    ajax: ADMIN_BETS_JSON_URL
    });

$("#undo-bet-btn").one("click", function() {
    $(this).click(function () { return false; });
});

$("#win-bet-btn").one("click", function() {
    $(this).click(function () { return false; });
});

$("#loss-bet-btn").one("click", function() {
    $(this).click(function () { return false; });
});

$("#tie-bet-btn").one("click", function() {
    $(this).click(function () { return false; });
});

$('#undoPropBet').on('show.bs.modal', function (e) {
    // get the bet text and place it in the modal
    var betText = $(e.relatedTarget).attr('data-id1');
    var betUser = $(e.relatedTarget).attr('data-id2');

    $("#betId").html(betText);
    $("#betUser").html(betUser);

    // get the href link with bet id and place it in the href
    $(this).find('.btn-warning').attr('href', $(e.relatedTarget).data('href'));
});
{% endblock %}

cfbets/bets/templates/bets/base_all_bets.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_head %}
<script type="text/javascript">
    var ALL_BETS_JSON_URL = '{% url "bets:all_bets_json" %}';
    // translations for datatables

    var dt_language = {
        "emptyTable":     "{% trans "No data available in table" %}",
        "info":           "{% trans "Showing _START_ to _END_ of _TOTAL_ entries" %}",
        "infoEmpty":      "{% trans "Showing 0 to 0 of 0 entries" %}",
        "infoFiltered":   "{% trans "(filtered from _MAX_ total entries)" %}",
        "infoPostFix":    "",
        "thousands":      ",",
        "lengthMenu":     "{% trans "Show _MENU_ entries" %}",
        "loadingRecords": "{% trans "Loading..." %}",
        "processing":     "{% trans "Processing..." %}",
        "search":         "{% trans "Search:" %}",
        "zeroRecords":    "{% trans "No matching records found" %}",
        "paginate": {
            "first":      "{% trans "First" %}",
            "last":       "{% trans "Last" %}",
            "next":       "{% trans "Next" %}",
            "previous":   "{% trans "Previous" %}"
        },
        "aria": {
            "sortAscending":  "{% trans ": activate to sort column ascending" %}",
            "sortDescending": "{% trans ": activate to sort column descending" %}"
        }
    }
</script>
{% endblock %}

{% block base_content %}
<div class="container">
<h1>All Bets</h1>

    <div class="container">
        <h3>Active Bets</h3>
        {% if all_active_bets %}
            <p>Currently active bets across all users. These don't have a winner marked yet.</p>
            <table class="table table-striped table-bordered table-condensed" id="currentActive">
                <thead>
                    <tr>
                        <th>Proposer</th>
                        <th>Proposee</th>
                        <th>Prop Bet</th>
                        <th>Wager</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bet in all_active_bets %}
                    <tr>
                        <td>{{ bet.accepted_prop.user.get_full_name }}</td>
                        <td>{{ bet.accepted_user.get_full_name }}</td>
                        <td>{{ bet.accepted_prop.prop_text }}</td>
                        <td>${{ bet.accepted_prop.prop_wager }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
                <p>No active bets?! Probe the group for participation.</p>
        {% endif %}
    </div>

    <div class="container">
        <h3>Completed Bets</h3>
        <p>All closed accepted bets. These are accepted bets that have a winner marked (aka closed).</p>
        <table class="table table-striped table-bordered table-condensed" id="closedAccepted">
            <thead>
                <tr>
                    <th>{% trans "Proposer" %}</th>
                    <th>{% trans "Proposee" %}</th>
                    <th>{% trans "Prop Bet" %}</th>
                    <th>{% trans "Wager" %}</th>
                    <th>{% trans "Winner" %}</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

</div>
{% endblock %}

{% block morejs %}
var dt_table = $('#closedAccepted').dataTable({
    language: dt_language,  // global variable defined in html
    order: [],
    lengthMenu: [10, 25, 50, 100],
    columnDefs: [
        {orderable: true,
        searchable: true,
        className: "center",
        targets: [0, 1, 2, 3]
        },
        {orderable: false,
        targets: -1
        }
    ],
    searching: true,
    processing: true,
    serverSide: true,
    stateSave: false,
    ajax: ALL_BETS_JSON_URL
});
{% endblock %}

cfbets/bets/templates/bets/base_open_bets.html
{% extends "base.html" %}

{% block base_content %}
<div class="container">
<h1>Open Bets</h1>

    <div class="container">
    {% if open_bets %}
        <p>These are all the open bets from other users. Accept these bets with reckless abandon.
        <p>
        <table class="table table-striped table-bordered table-condensed table-responsive" id=openBets>
            <thead>
                <tr>
                    <th>Prop Bet</th>
                    <th>User</th>
                    <th>Wager</th>
                    <th>Bets Remain</th>
                    <th>End Date</th>
                </tr>
            </thead>
            <tbody>
                {% for bet in open_bets %}
                    <tr>
                        <td>
                            {{ bet.prop_text }}
                            {% if bet in new_bets %}
                                <span class="badge">new</span>
                            {% endif %}

                            {% if bet in closing_soon_bets %}
                                <span class="badge">expiring</span>
                            {% endif %}

                            <div class="acceptBetButton" style="padding:10px 10px 0px 0px">
                                <a href="#" data-href="/bets/accept_prop_bet?id={{ bet.id }}"
                                    data-target="#acceptBet" data-toggle="modal"
                                    data-id1="{{ bet.prop_text }}"
                                    data-id2="{{ bet.user.get_full_name }}"
                                    data-id3="{{ bet.prop_wager }}"
                                    data-id4="{{ bet.id }}"
                                    title="Accept prop bet"
                                    class="btn btn-success btn-sm open-AcceptBet">Accept</a>
                            </div>
                        </td>
                        <td>{{ bet.user.get_full_name }}</td>
                        <td>${{ bet.prop_wager }}</td>
                        <td>{{ bet.remaining_wagers }}</td>
                        <td>{{ bet.end_date|date:"M d Y H:i" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p>There aren't any open bets to accept. This makes me sad. Email the group to get to work.</p>
        {% endif %}
    </div>

</div>

<!-- Accept bet modal -->
<div class="modal fade" id="acceptBet" tabindex="-1" role="dialog" aria-labelledby="AcceptBet">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="AcceptBet">Accept Bet</h4>
            </div>
            <div class="modal-body">
                <span id="duplicateBet"></span>
                <p>Accept <strong>$<span id="betAmount"></span></strong> bet
                    "<strong><span id="betId"></span>"</strong>
                    proposed by <span id="betUser"></span>?
                </p>
                <p><small><i>Note: You are betting <strong>against</strong> this prop bet. This action can't be undone.</i></small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a class="btn btn-success" id="accept-prop-btn">Accept Bet</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block morejs %}
$("#accept-prop-btn").one("click", function() {
    $(this).click(function () { return false; });
});

$('#acceptBet').on('show.bs.modal', function (e) {
    // remove any previous duplicate bet info
    $("#duplicateBet").html('');

    // get the bet text and place it in the modal
    var betText = $(e.relatedTarget).attr('data-id1');
    var betUser = $(e.relatedTarget).attr('data-id2');
    var betAmount = $(e.relatedTarget).attr('data-id3');

    $("#betId").html(betText);
    $("#betUser").html(betUser);
    $("#betAmount").html(betAmount);

    // get the href link with bet id and place it in the href
    $(this).find('.btn-success').attr('href', $(e.relatedTarget).data('href'));

    // check to see if you've already accepted this bet
    var id = $(e.relatedTarget).attr('data-id4');

    $.ajax({
        url: '/bets/check_duplicate_bet/',
        type: 'POST',
        data: {id: id},
        success: function(json){
            console.log(json);
            if (json.is_duplicate == "True")
            {
                $("#duplicateBet").html('<div class="alert alert-info">' +
                    '<span class="glyphicon glyphicon-info-sign"></span>' +
                    'You have accepted this bet at least once before. ' +
                    'Are you that confident?</div>');
            }
        },
        error: function(){
            alert("issue with duplicate bet checking. id: " + id);
        }
    });
});

$('#openBets').dataTable( {
    "order": [],
    "paging": false
});

{% endblock %}